name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
      - name: Install packages
        run: npm install
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy Storybook
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Build UI Package
        run: npm run build:ui
      - name: Release FastPay UI
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
